---
- name: Tests
  hosts: fireco_server
  remote_user: pi
  become: true
  tasks:

    - name: remove docker-py
      pip:
        name: docker-py
        state: absent
    - name: Install docker python module
      pip:
        name: "docker-compose==1.12.0"

    - name: Initialisation dossier temporaire
      file:
        path: "/tmp/fireco-install/"
        state: directory
        recurse: yes

    - name: Téléchargement script Docker
      get_url:
        url: https://get.docker.com
        dest: "/tmp/fireco-install/docker.sh"
        mode: 7777

    - name: Installation Docker
      shell: /tmp/fireco-install/docker.sh

    - name: Chargement de l'image fireco-update
      shell: docker pull lyoko17220/fireco-update

    - name: Chargement de l'image fireco-worker
      shell: docker pull lyoko17220/fireco-worker

    - name: Création dossier d'échange avec le Worker
      file:
        path: "/home/pi/firecoworker"
        state: directory
        recurse: yes
        mode: 0777

    - name: Stoppage de tout les containers
      shell: docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)

    - name: Lancement fireco-update
      shell: docker run -d -p 8081:8081 -p 9002:9001 -v /home/pi/firecoworker:/data --name fireco-updater-c lyoko17220/fireco-update

    - name: Initialisation de l'updater (attente app Worker)
      pause:
          minutes: 3

    - name: Lancement fireco-worker
      shell: docker run -d -p 8082:8082 -p 9001:9001 -v /home/pi/firecoworker:/data --name fireco-worker-c lyoko17220/fireco-worker

...
